require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
end

target 'IstanbulCicekleri' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Insider Mobile SDK core
  pod 'InsiderMobile', '~> 14.0'
  pod 'InsiderMobileAdvancedNotification', '~> 2.0'

  # Firebase pods
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCrashlytics', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true

  target 'IstanbulCicekleriTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        # Sandbox hatası için tüm target'lara ekle
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
end

# Notification extensions for Insider rich push
# NOTE: InsiderNotificationContent ve InsiderNotificationService target'ları
# henüz Xcode projesinde native target olarak eklenmedi.
# Xcode'dan File > New > Target ile ekledikten sonra aşağıdaki satırları açın:
# target 'InsiderNotificationContent' do
#   pod 'InsiderMobileAdvancedNotification', '~> 2.0'
# end
# target 'InsiderNotificationService' do
#   pod 'InsiderMobileAdvancedNotification', '~> 2.0'
# end
