// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/murat/IstanbulCicekleri/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/murat/IstanbulCicekleri/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('IstanbulCicekleri', appParameters);
});
require('/Users/murat/IstanbulCicekleri/index.js');